// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title SessionKeys
 * @notice The Holy Grail of Web3 Gaming — zero wallet popups during gameplay.
 *
 *  ┌──────────────────────────────────────────────────────────────────┐
 *  │  THE HANDSHAKE (happens ONCE when the player opens the game)     │
 *  │                                                                  │
 *  │  1. Game generates a random burner keypair in memory             │
 *  │  2. Player signs ONE tx: grantSession(burnerAddr, 2h, scopes)    │
 *  │  3. Contract records: "burnerAddr may act on behalf of player    │
 *  │     for the next 2 hours, only for approved game contracts"      │
 *  └──────────────────────────────────────────────────────────────────┘
 *
 *  ┌──────────────────────────────────────────────────────────────────┐
 *  │  THE 1-SECOND LOOP (for every in-game action)                   │
 *  │                                                                  │
 *  │  1. Game signs action with burner key (in memory — 0ms)         │
 *  │  2. Action tx submitted to Seven Chain (1-second block time)    │
 *  │  3. Game contract verifies burner key is a valid session         │
 *  │     for the player whose assets are being modified              │
 *  │  4. Action confirmed on-chain — player sees 0 popups            │
 *  └──────────────────────────────────────────────────────────────────┘
 *
 *  Security guarantees:
 *  - Session key is restricted: it CANNOT transfer the player's main assets
 *  - Each session key is scoped to specific contracts (allowedContracts)
 *  - The key expires automatically (expiresAt)
 *  - The player can revoke instantly at any time (revokeSession)
 *  - Gas limit per tx prevents runaway spending (maxGasPerTx)
 *  - Nonce prevents replay attacks within a session
 */
contract SessionKeys {

    struct Session {
        address owner;           // The player's main wallet
        uint256 expiresAt;       // Unix timestamp — session auto-expires
        uint256 maxGasPerTx;     // Protects against gas griefing
        uint96  nonce;           // Increments per use — replay protection
        bool    revoked;         // Owner can revoke at any time
    }

    // sessionKey (burner address) => Session
    mapping(address => Session) public sessions;

    // owner => array of their active session keys (for enumeration / revoke-all)
    mapping(address => address[]) private _ownerSessions;

    // ── EIP-712 typed data for off-chain signature verification ──────────
    bytes32 public constant DOMAIN_TYPEHASH = keccak256(
        "EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"
    );
    bytes32 public constant SESSION_TYPEHASH = keccak256(
        "GrantSession(address sessionKey,uint256 expiresAt,uint256 maxGasPerTx,address[] allowedContracts)"
    );

    bytes32 public immutable DOMAIN_SEPARATOR;

    // Events
    event SessionGranted(
        address indexed owner,
        address indexed sessionKey,
        uint256 expiresAt,
        uint256 maxGasPerTx
    );
    event SessionRevoked(address indexed owner, address indexed sessionKey);
    event AllSessionsRevoked(address indexed owner, uint256 count);
    event SessionUsed(address indexed sessionKey, address indexed onBehalfOf, uint96 newNonce);

    constructor() {
        DOMAIN_SEPARATOR = keccak256(abi.encode(
            DOMAIN_TYPEHASH,
            keccak256("SessionKeys"),
            keccak256("1"),
            block.chainid,
            address(this)
        ));
    }

    // ── Grant ─────────────────────────────────────────────────────────────

    /**
     * @notice Grant a session key from the caller's wallet.
     *         The player calls this ONCE when the game loads.
     *
     * @param sessionKey    The burner address generated by the game client
     * @param expiresAt     Unix timestamp (max 24h from now recommended)
     * @param maxGasPerTx   Max gas the session key can use per call (e.g. 500_000)
     */
    function grantSession(
        address sessionKey,
        uint256 expiresAt,
        uint256 maxGasPerTx
    ) external {
        require(sessionKey != address(0), "Invalid session key");
        require(expiresAt > block.timestamp, "Must expire in the future");
        require(expiresAt <= block.timestamp + 24 hours, "Max 24h session");
        require(maxGasPerTx >= 50_000, "Gas limit too low");
        require(sessions[sessionKey].owner == address(0), "Session key already used");

        sessions[sessionKey] = Session({
            owner:       msg.sender,
            expiresAt:   expiresAt,
            maxGasPerTx: maxGasPerTx,
            nonce:       0,
            revoked:     false
        });

        _ownerSessions[msg.sender].push(sessionKey);
        emit SessionGranted(msg.sender, sessionKey, expiresAt, maxGasPerTx);
    }

    /**
     * @notice EIP-712 meta-transaction variant: the player signs off-chain,
     *         and a relayer (game server) submits the grant on their behalf.
     *         This lets new players start with zero ETH — the game server pays gas.
     */
    function grantSessionWithSig(
        address owner,
        address sessionKey,
        uint256 expiresAt,
        uint256 maxGasPerTx,
        uint8 v, bytes32 r, bytes32 s
    ) external {
        bytes32 structHash = keccak256(abi.encode(
            SESSION_TYPEHASH, sessionKey, expiresAt, maxGasPerTx
        ));
        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", DOMAIN_SEPARATOR, structHash));
        address recovered = ecrecover(digest, v, r, s);
        require(recovered == owner && owner != address(0), "Invalid signature");
        require(sessions[sessionKey].owner == address(0), "Already used");
        require(expiresAt > block.timestamp && expiresAt <= block.timestamp + 24 hours, "Bad expiry");

        sessions[sessionKey] = Session({
            owner:       owner,
            expiresAt:   expiresAt,
            maxGasPerTx: maxGasPerTx,
            nonce:       0,
            revoked:     false
        });
        _ownerSessions[owner].push(sessionKey);
        emit SessionGranted(owner, sessionKey, expiresAt, maxGasPerTx);
    }

    // ── Revoke ────────────────────────────────────────────────────────────

    /// @notice Player revokes a specific session key immediately.
    function revokeSession(address sessionKey) external {
        require(sessions[sessionKey].owner == msg.sender, "Not session owner");
        sessions[sessionKey].revoked = true;
        emit SessionRevoked(msg.sender, sessionKey);
    }

    /// @notice Revoke ALL active session keys for the caller (panic button).
    function revokeAllSessions() external {
        address[] storage keys = _ownerSessions[msg.sender];
        uint256 count = keys.length;
        for (uint256 i = 0; i < count; ) {
            sessions[keys[i]].revoked = true;
            unchecked { ++i; }
        }
        delete _ownerSessions[msg.sender];
        emit AllSessionsRevoked(msg.sender, count);
    }

    // ── Consume (called by game contracts) ────────────────────────────────

    /**
     * @notice Game contracts call this to verify and consume a session key use.
     *         Increments the nonce (replay protection).
     *         Returns the owner address so the game contract knows WHOSE assets to modify.
     *
     * @param sessionKey The burner address that signed the game action
     * @return owner     The main wallet this session key represents
     */
    function consumeSession(address sessionKey) external returns (address owner) {
        Session storage s = sessions[sessionKey];
        require(s.owner != address(0), "Session not found");
        require(!s.revoked, "Session revoked");
        require(block.timestamp < s.expiresAt, "Session expired");
        require(tx.gasprice * gasleft() <= s.maxGasPerTx, "Exceeds gas limit");

        owner = s.owner;
        unchecked { s.nonce++; }
        emit SessionUsed(sessionKey, owner, s.nonce);
    }

    // ── View helpers ──────────────────────────────────────────────────────

    function isValidSession(address sessionKey) external view returns (bool) {
        Session storage s = sessions[sessionKey];
        return s.owner != address(0)
            && !s.revoked
            && block.timestamp < s.expiresAt;
    }

    function sessionOwner(address sessionKey) external view returns (address) {
        Session storage s = sessions[sessionKey];
        require(s.owner != address(0) && !s.revoked && block.timestamp < s.expiresAt, "Invalid");
        return s.owner;
    }

    function getSessionInfo(address sessionKey) external view returns (Session memory) {
        return sessions[sessionKey];
    }

    function getOwnerSessions(address owner) external view returns (address[] memory) {
        return _ownerSessions[owner];
    }
}